name: Atualiza data no service-worker

on:
  push:
    branches: [main]

permissions:
  contents: write  # ⬅️ ESSENCIAL para permitir commits/push

jobs:
  atualizar-sw:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Atualizar data no service-worker.js
        run: |
          DATA=$(date "+%Y-%m-%d %H:%M")
          sed -i "s|// Última atualização: .*|// Última atualização: $DATA|" service-worker.js

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit e push da nova data
        run: |
          git add service-worker.js
          git commit -m "Atualiza data no service-worker"
          git push