name: Atualiza data no service-worker

on:
  push:
    paths:
      - 'service-worker.js'

jobs:
  atualizar-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Substituir data de atualização no service-worker.js
        run: |
          data=$(date '+%Y-%m-%d %H:%M')
          sed -i "s|// Última atualização: .*|// Última atualização: $data|" service-worker.js

      - name: Commit e push da atualização
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Atualiza data no service worker [$data]"
          git push